export const REGION_CITY = [
  {
    id: "seoul",
    label: "서울",
    cities: [
      { id: "seoulGangnam", label: "강남구" },
      { id: "seoulGangdong", label: "강동구" },
      { id: "seoulGangbuk", label: "강북구" },
      { id: "seoulGangseo", label: "강서구" },
      { id: "seoulGwanak", label: "관악구" },
      { id: "seoulGwangjin", label: "광진구" },
      { id: "seoulGuro", label: "구로구" },
      { id: "seoulGeumcheon", label: "금천구" },
      { id: "seoulNowon", label: "노원구" },
      { id: "seoulDobong", label: "도봉구" },
      { id: "seoulDongdaemun", label: "동대문구" },
      { id: "seoulDongjak", label: "동작구" },
      { id: "seoulMapo", label: "마포구" },
      { id: "seoulSeodaemun", label: "서대문구" },
      { id: "seoulSeocho", label: "서초구" },
      { id: "seoulSeongdong", label: "성동구" },
      { id: "seoulSeongbuk", label: "성북구" },
      { id: "seoulSongpa", label: "송파구" },
      { id: "seoulYangcheon", label: "양천구" },
      { id: "seoulYeongdeungpo", label: "영등포구" },
      { id: "seoulYongsan", label: "용산구" },
      { id: "seoulEunpyeong", label: "은평구" },
      { id: "seoulJongno", label: "종로구" },
      { id: "seoulJung", label: "중구" },
      { id: "seoulJungnang", label: "중랑구" },
    ],
  },
  {
    id: "busan",
    label: "부산",
    cities: [
      { id: "busanGangseo", label: "강서구" },
      { id: "busanGeumjeong", label: "금정구" },
      { id: "busanGijang", label: "기장군" },
      { id: "busanNam", label: "남구" },
      { id: "busanDong", label: "동구" },
      { id: "busanDongnae", label: "동래구" },
      { id: "busanBusanjin", label: "부산진구" },
      { id: "busanBuk", label: "북구" },
      { id: "busanSasang", label: "사상구" },
      { id: "busanSaha", label: "사하구" },
      { id: "busanSeo", label: "서구" },
      { id: "busanSuyeong", label: "수영구" },
      { id: "busanYeonje", label: "연제구" },
      { id: "busanJung", label: "중구" },
      { id: "busanHaeundae", label: "해운대구" },
    ],
  },
  {
    id: "daegu",
    label: "대구",
    cities: [
      { id: "daeguNam", label: "남구" },
      { id: "daeguDalseo", label: "달서구" },
      { id: "daeguDalseong", label: "달성군" },
      { id: "daeguDong", label: "동구" },
      { id: "daeguBuk", label: "북구" },
      { id: "daeguSeo", label: "서구" },
      { id: "daeguSuseong", label: "수성구" },
      { id: "daeguJung", label: "중구" },
    ],
  },
  {
    id: "incheon",
    label: "인천",
    cities: [
      { id: "incheonGyeyang", label: "계양구" },
      { id: "incheonNamdong", label: "남동구" },
      { id: "incheonMichuhol", label: "미추홀구" },
      { id: "incheonBupyeong", label: "부평구" },
      { id: "incheonSeo", label: "서구" },
      { id: "incheonYeonsu", label: "연수구" },
      { id: "incheonJung", label: "중구" },
    ],
  },
  {
    id: "gwangju",
    label: "광주",
    cities: [
      { id: "gwangjuGwangsan", label: "광산구" },
      { id: "gwangjuNam", label: "남구" },
      { id: "gwangjuDong", label: "동구" },
      { id: "gwangjuBuk", label: "북구" },
      { id: "gwangjuSeo", label: "서구" },
    ],
  },
  {
    id: "daejeon",
    label: "대전",
    cities: [
      { id: "daejeonDaedeok", label: "대덕구" },
      { id: "daejeonDong", label: "동구" },
      { id: "daejeonSeo", label: "서구" },
      { id: "daejeonYuseong", label: "유성구" },
      { id: "daejeonJung", label: "중구" },
    ],
  },
  {
    id: "ulsan",
    label: "울산",
    cities: [
      { id: "ulsanNam", label: "남구" },
      { id: "ulsanDong", label: "동구" },
      { id: "ulsanBuk", label: "북구" },
      { id: "ulsanUlju", label: "울주군" },
      { id: "ulsanJung", label: "중구" },
    ],
  },
  {
    id: "sejong",
    label: "세종",
    cities: [{ id: "sejong", label: "전체" }],
  },
  {
    id: "gyeonggi",
    label: "경기",
    cities: [
      { id: "goyang", label: "고양시" },
      { id: "gwacheon", label: "과천시" },
      { id: "gwangmyeong", label: "광명시" },
      { id: "gwangju", label: "광주시" },
      { id: "guri", label: "구리시" },
      { id: "gunpo", label: "군포시" },
      { id: "gimpo", label: "김포시" },
      { id: "namyangju", label: "남양주시" },
      { id: "dongducheon", label: "동두천시" },
      { id: "bucheon", label: "부천시" },
      { id: "seongnam", label: "성남시" },
      { id: "suwon", label: "수원시" },
      { id: "siheung", label: "시흥시" },
      { id: "ansan", label: "안산시" },
      { id: "anseong", label: "안성시" },
      { id: "anyang", label: "안양시" },
      { id: "yangju", label: "양주시" },
      { id: "osan", label: "오산시" },
      { id: "yongin", label: "용인시" },
      { id: "uiwang", label: "의왕시" },
      { id: "uijeongbu", label: "의정부시" },
      { id: "icheon", label: "이천시" },
      { id: "paju", label: "파주시" },
      { id: "pyeongtaek", label: "평택시" },
      { id: "pocheon", label: "포천시" },
      { id: "hanam", label: "하남시" },
      { id: "hwaseong", label: "화성시" },
    ],
  },
  {
    id: "gangwon",
    label: "강원",
    cities: [
      { id: "gangneung", label: "강릉시" },
      { id: "donghae", label: "동해시" },
      { id: "sokcho", label: "속초시" },
      { id: "yanggu", label: "양구군" },
      { id: "yeongwol", label: "영월군" },
      { id: "wonju", label: "원주시" },
      { id: "chuncheon", label: "춘천시" },
      { id: "hongcheon", label: "홍천군" },
    ],
  },
  {
    id: "chungbuk",
    label: "충북",
    cities: [
      { id: "eumseong", label: "음성군" },
      { id: "jecheon", label: "제천시" },
      { id: "jeungpyeong", label: "증평군" },
      { id: "cheongju", label: "청주시" },
      { id: "chungju", label: "충주시" },
    ],
  },
  {
    id: "chungnam",
    label: "충남",
    cities: [
      { id: "gyeryong", label: "계룡시" },
      { id: "gongju", label: "공주시" },
      { id: "nonsan", label: "논산시" },
      { id: "dangjin", label: "당진시" },
      { id: "boryeong", label: "보령시" },
      { id: "seosan", label: "서산시" },
      { id: "asan", label: "아산시" },
      { id: "yesan", label: "예산군" },
      { id: "cheonan", label: "천안시" },
    ],
  },
  {
    id: "jeonbuk",
    label: "전북",
    cities: [
      { id: "gunsan", label: "군산시" },
      { id: "gimje", label: "김제시" },
      { id: "wanju", label: "완주군" },
      { id: "iksan", label: "익산시" },
      { id: "jeonju", label: "전주시" },
      { id: "jeongeup", label: "정읍시" },
    ],
  },
  {
    id: "jeonnam",
    label: "전남",
    cities: [
      { id: "gwangyang", label: "광양시" },
      { id: "naju", label: "나주시" },
      { id: "mokpo", label: "목포시" },
      { id: "muan", label: "무안군" },
      { id: "suncheon", label: "순천시" },
      { id: "yeosu", label: "여수시" },
      { id: "haenam", label: "해남군" },
    ],
  },
  {
    id: "gyeongbuk",
    label: "경북",
    cities: [
      { id: "gyeongsan", label: "경산시" },
      { id: "gyeongju", label: "경주시" },
      { id: "gumi", label: "구미시" },
      { id: "gimcheon", label: "김천시" },
      { id: "mungyeong", label: "문경시" },
      { id: "sangju", label: "상주시" },
      { id: "andong", label: "안동시" },
      { id: "yecheon", label: "예천군" },
      { id: "chilgok", label: "칠곡군" },
      { id: "pohang", label: "포항시" },
    ],
  },
  {
    id: "gyeongnam",
    label: "경남",
    cities: [
      { id: "geoje", label: "거제시" },
      { id: "goseong", label: "고성군" },
      { id: "gimhae", label: "김해시" },
      { id: "sacheon", label: "사천시" },
      { id: "yangsan", label: "양산시" },
      { id: "jinju", label: "진주시" },
      { id: "changwon", label: "창원시" },
      { id: "tongyeong", label: "통영시" },
    ],
  },
  {
    id: "jejudo",
    label: "제주",
    cities: [
      { id: "seogwipo", label: "서귀포시" },
      { id: "jeju", label: "제주시" },
    ],
  },
];

export const QUERY_KEY = {
  box: {
    list: ["box", "list"],
    byId: (boxId: string) => ["box", "list", boxId],
  },
  bookmark: {
    list: ["bookmark", "list"],
  },
};
